// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1, arg2, arg3) {
  return window['go']['backend']['App']['AddTodo'](arg1, arg2, arg3);
}

export function DeleteTodo(arg1) {
  return window['go']['backend']['App']['DeleteTodo'](arg1);
}

export function GetTodos(arg1) {
  return window['go']['backend']['App']['GetTodos'](arg1);
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function ToggleTodo(arg1) {
  return window['go']['backend']['App']['ToggleTodo'](arg1);
}

export function UpdateTodo(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateTodo'](arg1, arg2, arg3, arg4);
}
