// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string,arg2:string,arg3:any):Promise<main.Todo>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetTodos(arg1:any):Promise<Array<Record<string, any>>>;

export function Greet(arg1:string):Promise<string>;

export function ToggleTodo(arg1:number):Promise<void>;
